import Head from "next/head";
import Image from "next/image";
import CoinGecko from "coingecko-api";
import { useState } from "react";

// initialize coin gecko client
const coinGeckoClient = new CoinGecko();

const formatDecimal = (number) => {
  return `${new Number(number.toFixed(2))}%`;
};
const formatDollar = (number, maximumSignificantDigits) => {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "usd",
    maximumSignificantDigits,
  }).format(number);
};

export default function Home({ response, chosenIndex }) {
  const [search, setSearch] = useState("");
  const handleChange = (e) => {
    setSearch(e.target.value);
  };
  const filteredCoins = response.data.filter((coin) => {
    return coin.name.toLowerCase().includes(search.toLowerCase());
  });

  return (
    <div>
      <Head>
        <title>Coinmarketcap clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito+Sans:ital@1&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="container">
        <h1>{quotes[chosenIndex]}</h1>
        <form>
          <input
            type="text"
            placeholder="Search coin names"
            className="coin-input"
            onChange={handleChange}
          />
        </form>
        <div className="coin-image"></div>
        <div className="coin-image2"></div>
        <table className="table">
          <thead className="head">
            <tr>
              <th>Symbol</th>
              <th>24H Change</th>
              <th>Price</th>
              <th>Market Cap</th>
            </tr>
          </thead>
          <tbody className="body">
            {filteredCoins.map((coin) => {
              return (
                <tr key={coin.id}>
                  <td>
                    <img
                      src={coin.image}
                      alt={coin.symbol}
                      style={{ width: 25, height: 25, marginRight: 10 }}
                    />
                    {coin.symbol.toUpperCase()}
                  </td>
                  <td>
                    <span
                      className={
                        coin.price_change_percentage_24h > 0
                          ? "text-success"
                          : "text-danger"
                      }
                    >
                      {formatDecimal(coin.price_change_percentage_24h)}
                    </span>
                  </td>
                  <td>{formatDollar(coin.current_price, 20)}</td>
                  <td>{formatDollar(coin.market_cap, 12)}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const params = {
    order: CoinGecko.ORDER.MARKET_CAP_DESC,
  };
  const response = await coinGeckoClient.coins.markets({ params });
  const chosenIndex = Math.floor(Math.random() * quotes.length);
  return {
    props: {
      response,
      chosenIndex,
    },
  };
}

const quotes = [
  "“Markets can remain irrational longer than you can remain solvent.” — John Maynard Keynes",
  "“Invest in yourself. Your career is the engine of your wealth.” — Paul Clitheroe",
  "“Most investors want to do today what they should have done yesterday.”– Larry Summers",
  "“The broker said the stock was “poised to move.” Silly me, I thought he meant up.” –Randy Thurman",
  "“Never trust a stockbroker under the age of 60. “– David R. Wommack",
  "“Successful investing is anticipating the anticipations of others.” — John Maynard Keynes",
  "“The markets are unforgiving, and emotional trading always results in losses.” — Alexander Elder",
  "“October: This is one of the peculiarly dangerous months to speculate in stocks. The others are July, January, September, April, November, May, March, June, December, August and February.” —  Mark Twain",
  "“The whole secret to winning big in the stock market is not to be right all the time, but to lose the least amount possible when you’re wrong.” — William J. O’Neil",
  "“No profession requires more hard work, intelligence, patience, and mental discipline than successful speculation.” — Robert Rhea",
  "“There are old traders and there are bold traders, but there are very few old, bold traders.” — Ed Seykota",
  "“When an investor focuses on short-term investments, he or she is observing the variability of the portfolio, not the returns – in short, being fooled by randomness.” — Nassim Nicholas Taleb",
  "“Buy when everyone else is selling and hold when everyone else is buying. This is not merely a catchy slogan. It is the very essence of successful investments.” — Jean Paul Getty",
  "“If investing is entertaining, if you’re having fun, you’re probably not making money. Good investing is boring.” — George Soros",
  "“When buying shares, ask yourself, would you buy the whole company?” — Rene Rivkin",
  "“We need to stop pretending that we can divine the future, and instead concentrate on understanding the present, and preparing for the unknown.” — James Montier",
  "“Investing should be more like watching paint dry or watching grass grow. If you want excitement, take $800 and go to Las Vegas.” — Paul Anthony Samuelson",
  "“If you’re saving, you’re succeeding.” — Steve Burkholder",
  "“The stock market is filled with individuals who know the price of everything, but the value of nothing.” — Philip Fisher",
  "“Every once in a while, the market does something so stupid it takes your breath away.” — Jim Cramer",
  "“How many millionaires do you know who have become wealthy by investing in savings accounts? I rest my case.” — Robert G. Allen",
  "“Compound interest is the eighth wonder of the world. He who understands it, earns it; he who doesn’t, pays it.” — Albert Einstein",
  "“An investment in knowledge always pays the best interest.” — Benjamin Franklin",
  "“If investing is entertaining, if you’re having fun, you’re probably not making any money. Good investing is boring.” — George Soros",
  "“Investing should be more like watching paint dry or watching grass grow. If you want excitement, take $800 and go to Las Vegas.” — Paul Samuelson",
  " “Value investing is at its core the marriage of a contrarian streak and a calculator.” — Seth Klarman",
  "“While some might mistakenly consider value investing a mechanical tool for identifying bargains, it is actually a comprehensive investment philosophy that emphasizes the need to perform in-depth fundamental analysis, pursue long-term investment results, limit risk, and resist crowd psychology.” — Seth Klarman",
];
